sudo: required
language: node_js
node_js:
- '8'
addons:
  hosts:
    - moztw.org
cache:
  - apt
  - npm
  - nvm
branches:
  only:
  - production
before_deploy:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2
  - sudo a2enmod rewrite
  - sudo a2enmod include
  - sudo rm -rf /etc/apache2/sites-available/*
  - cat ./.build/moztw-apache.conf | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/000-default.conf > /dev/null
  - echo "ServerName moztw.org" | sudo tee /etc/apache2/conf-available/servername.conf > /dev/null
  - sudo a2enconf servername
  - sudo a2ensite 000-default
  - sudo chmod -R 777 ~/
  - sudo chown -R www-data:www-data ~/
  - npm run patch
  - sudo service apache2 restart
  - npm run build
  - cp CNAME ./dist/moztw.org/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/moztw.org/
  on:
    branch: master
