LBPlayer.Lang.en = {
	Play: "play",
	Pause: "pause",
	Stop: "stop",
	Volume: "set volume",
	Mute: "mute",
	UnMute: "unmute",
	Fullscreen: "set to in-browser fullscreen view",
	Smallscreen: "set to minimal view",
	PlaybackRate_title: "playback rate",
	PlaybackRate_inner: "1x",
	PlaybackRate_to: "set playback rate to: ",
	PlaybackRate_2: "2x",
	PlaybackRate_1: "1x",
	PlaybackRate_05: unescape("%BD")+"x",
	PlaybackRate_025: unescape("%BC")+"x",
	Subtitle_title: "change subtitle",
	Subtitle_inner: "CC",
	Subtitle_set: "on/off",
	Subtitle_onoff: "set subtitle on/off",
	Subtitle_to: "change subtitle language to: ",
	Sources_title: "change quality",
	Sources_inner: "SD",
	Sources_to: "change quality to: ",
	Playlist_title: "choose a video from playlist",
	Playlist_inner: "PL",
	Playlist_to: "switch to playlist-item ",
	EmbedInfo: "&lt;<span class=\"bold\">embed</span>&gt;",
	EmbedInfoTitle: "Embedding information for video",
	EmbedVideo: "Copy <span class=\"bold\">embed-code</span> of video",
	EmbedVideoTitle: "Copy embed-code of video",
	EmbedURL: "Copy <span class=\"bold\">backlink url</span> of page",
	EmbedURLTitle: "Copy backling url of page",
	EmbedCodeTxt: "Copy the code above to integrate to your page.",
	EmbedBtn: "close",
}